### ISSUE TITLE
[BUG] FTL project root not found

### ISSUE THREAD

**Issue by made2591** [terramate-io/terramate#1003]
**Describe the bug**
Hi guys, just started a toy project with terramate, I lost 15 minutes in understanding that `terramate create <whatever>` requires to be run inside a `git init`-ialized folder

**To Reproduce**

1. Follow the guidelines [here](https://terramate.io/docs/cli/getting-started/)
2. Run the command `terramate create mysite`
3. See error `FTL project root not found`

**Expected behavior**
I expected the error message to be more self-explanatory or at least the guide stating that a git folder is strictly required even only to start with the simple walk-through

**Environment (please complete the following information):**
 - OS: MacOS Ventura
 - OS Version 13.4
 - Git Version 2.39.2
 - Terramate Version 0.3.0

**Comment by soerenmartius** [comment]
Hi @made2591,

Thanks for reporting this. This is actually not a bug but the desired behavior. If you run `terramate create` in a non-Git managed project, it requires you create a `terramate.tm.hcl`, which indicates the root of your Terramate project, which is otherwise detected by looking at the toplevel of your git repository.

I must agree that the exception needs to be improved. Also, the referred guide should explain the behavior more obviously.

**Comment by soerenmartius** [comment]
Updated the error message in https://github.com/terramate-io/terramate/pull/1004

**Comment by made2591** [comment]
thank you @soerenmartius for the fast answer! Actually, I was wrong or better, imprecise: the issue was raised because my terramate hcl file contained a typo in the file name - despite my twelve check before opening the issue - and terramate wasn't able to correctly init the project. Thank you very much for your effort 🙏

**Comment by soerenmartius** [comment]
Hi @made2591 

I updated the documentation in https://github.com/terramate-io/terramate/pull/1007/files also!
Don't forget to join our [Discord](http://terramate.io/discord) community if you want to talk to the team directly!

Again, thanks for reporting this issue!
