### ISSUE TITLE
[BUG] Experiment Clone Feature Improperly Clones Nested Stacks

### ISSUE THREAD

**Issue by donovanrost** [terramate-io/terramate#1174]
**Describe the bug**
I recognize that `clone` is experimental and that the docs do specify
> Note: Currently, `clone` does not support nested stacks. We will add this functionality in the future. 

This ticket just serves to document this behavior

When performing `terramate experimental clone` one would expect nested stacks to have their `stack.id` to have a freshly generated uuid, however the cloned nested stack inherits the the `stack.id` of the corresponding source stack. 

**To Reproduce**

1. Given the existence of a nested stack
2. Run command `terramate experimental clone <source> <target>
3. Observe that every nested stack has the same `stack.id` as the source nested stack

**Expected behavior**
When performing `terramate experimental clone` one would expect nested stacks to have their `stack.id` to have a freshly generated uuid, however the cloned nested stack inherits the the `stack.id` of the corresponding source stack. 

**Environment (please complete the following information):**
 - OS: Windows 
 - OS Version 10
 - Git Version: git version 2.40.1.windows.1
 - Terramate Version: 0.4.2

**Comment by soerenmartius** [comment]
Hi @donovanrost, 

Thanks for reaching out! This is a known limitation because the `clone` command is still experimental. However, we have a ticket in the backlog to support nested stacks. Let me align this with the team. I will get back to you later today with a potential timeline to get this implemented.

Thanks!

**Comment by soerenmartius** [comment]
Hi @donovanrost

We just merged deep cloning back to main and will release that feature in the upcoming `v0.4.3` which will be released in a couple of days.

You can now use the clone command to clone nested stacks or, in other words, entire environments. Imagine you develop a new service in staging that you want to role out to production. Instead of manually copying and pasting a bunch of stacks, updating the stack metadata, etc., clone now does this for you automatically. Often, users use the [stack.id(http://stack.id/) metadata property, which contains a stacks’ UUID in the Terramate Code Generation for, e.g., prefixing a state path for generated [Terraform Backend definition](https://github.com/terramate-io/terramate-examples/tree/main/01-keep-terraform-dry). The clone command will automatically update the UUID for all cloned stacks and trigger the code generation.
