### ISSUE TITLE
Script failed with terraform options

### ISSUE THREAD

**Issue by abtris** [terramate-io/terramate#1502]
**Describe the bug**
I need run terraform commands with multiple options as:

```
terraform init -backend-config='resource_group_name=rg-terraform-state' -backend-config='storage_account_name=tfstatestgactstore' -backend-config='container_name=tfstate' -backend-config='subscription_id=<redacted>'
```

and that doesn't work for me.

**To Reproduce**

1. Given context 'I create script function to run it'

```
script "init2" {
  description = "Run a Terraform Init"
  job {
    commands = [
      ["terraform", "init", "-backend-config='resource_group_name=rg-terraform-state'", "-backend-config='storage_account_name=tfstatestgactstore'", "-backend-config='container_name=tfstate'", "-backend-config='subscription_id=<redacted>'", "-upgrade"]
    ]
  }
}
```

3. Run command 'terramate script run --no-recursive init2'

```
╷
│ Error: Invalid backend configuration argument
│
│ The backend configuration argument "'resource_group_name" given on the command line is not expected for the selected backend type.
╵
```

**Expected behavior**

I think that should be run as as normal. I have to wrap to bash to make it work.

```
script "init" {
  description = "Run a Terraform Init"
  job {
    commands = [
      ["/bin/bash", "-c", <<-EOT
        set -e
        terraform init -backend-config='resource_group_name=rg-terraform-state' -backend-config='storage_account_name=tfstatestgactstore' -backend-config='container_name=tfstate' -backend-config='subscription_id=<redacted>' -upgrade
      EOT
      ]
    ]
  }
}
```

**Log Output**
Add logs from Terramate to help debug your problem.

**Environment (please complete the following information):**
 - OS: macOS
 - OS Version 13.6.4
 - Git Version git version 2.44.0
 - Terramate Version 0.4.6

**Comment by i4ki** [comment]
Hi @abtris 

The single quotes in your command is only needed when running it in the shell, because you want to make sure multi space arguments are not treated as multiple arguments by the target command (in this case `terraform init`). The shell interprets the single quotes and don't pass it forward to the command.

But in case of Terramate scripts, the `command` attribute is a `list of string`, so each item in the list is a command argument, so no risk of a multi space string becoming multiple arguments.

Whatever you put in the string, will be seen by the target command. Check the error that Terraform returned:
```
The backend configuration argument "'resource_group_name" given on the command ...
```
The single quote there ☝️ is wrong.

The code below is what you want:

```
script "init2" {
  description = "Run a Terraform Init"
  job {
    commands = [
      ["terraform", "init", "-backend-config=resource_group_name=rg-terraform-state", "-backend-config=storage_account_name=tfstatestgactstore", "-backend-config=container_name=tfstate", "-backend-config=subscription_id=<redacted>", "-upgrade"]
    ]
  }
}
```

Setting up a command in Terramate is similar to what you would do in other programming languages. So for example, in Go it would be:

```go
cmd := exec.Command("terraform", "init", "-backend-config=resource_group_name=rg-terraform-state", "-backend-config=storage_account_name=tfstatestgactstore", "-backend-config=container_name=tfstate", "-backend-config=subscription_id=<redacted>", "-upgrade")
```
If you provide the single quotes in the code above, you will receive the same Terraform error.

I agree that this sometimes is a bit confusing because we are so used to the shell syntax.
Let me know if this is clear.

**Comment by soerenmartius** [comment]
@abtris please let us know if this answered your question. We will close this issue soon otherwise! Thank you

**Comment by abtris** [comment]
Thanks, I will test it. Free to close it.

**Comment by abtris** [comment]
Works for me, thanks for help.
